### ISSUE TITLE
Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

### ISSUE THREAD

**Issue by gloryluu** [okta/okta-sdk-appauth-ios#42]
Warning on Xcode 9.2

**Comment by jmelberg-okta** [comment]
Thanks for reporting this issue @gloryluu! This is getting fixed with #28.

I'm going to include this in the `1.0.0` milestone and keep this open until that gets merged in.

**Comment by gloryluu** [comment]
I have upgraded and it seems the warning still exists in the dependency AppAuth. Could you update the OktaPodSpec as well?
